name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ⚡ Cache
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 🔨 Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Create env file
        run: mv .env.example .env

      - name: 🔎 Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      # - name: ⚙ Integration test
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --features "integration_tests"
